export const Genero = [
  "Ação",
  "Action RPG",
  "Aventura",
  "Exploração",
  "Ficção Científica",
  "Hack 'n Slash",
  "J-Horror",
  "JRPG",
  "Key",
  "Life Simulator",
  "Mundo Aberto",
  "Plataforma",
  "Psychological Horror",
  "RPG",
  "Sandbox",
  "Sobrevivência",
  "Soulslike",
  "Stealth Action",
  "Survival Horror"
];