export const Genero = [
    "Mundo Aberto",
    "Sandbox",
    "Survival Horror",
    "Life Simulator",
    "Ação",
    "Aventura",
    "Plataforma",
    "RPG",
    "JRPG",
    "Sobrevivência",
    "Key",
    "Exploração",
    "Hack 'n Slash",
    "Stealth Action",
    "Terror Psicológico",
    "J-Horror",
    "Action RPG",
    "Soulslike",
    "Ficção Científica",
  ];